src/AM/Bundle/BillingBundle/Entity/Contract.php
<?php

namespace AM\Bundle\BillingBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use AM\Bundle\UserBundle\Entity\User;

/**
 * Contract
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Contract
{
    const ANNUAL = 1;
    const QUARTERLY = 2;
    const BIMONTHLY = 3;
    const MONTHLY = 4;
    const WEEKLY = 5;

    public static $typeToHuman = [
        Contract::ANNUAL => 'Annual',
        Contract::QUARTERLY => 'Quaterly',
        Contract::BIMONTHLY => 'Bimonthly',
        Contract::MONTHLY => 'Monthly',
        Contract::WEEKLY => 'Weekly',
    ];

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var float
     *
     * @ORM\Column(name="amount", type="float")
     */
    private $amount = 0.00;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="startedAt", type="datetime")
     */
    private $startedAt;

    /**
     * @var string
     *
     * @ORM\Column(name="currency", type="string", length=4)
     */
    private $currency;

    /**
     * @var integer
     *
     * @ORM\Column(name="type", type="integer")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="AM\Bundle\BillingBundle\Entity\Contact", inversedBy="contracts")
     * @ORM\JoinColumn(name="contact", referencedColumnName="id")
     */
    protected $contact;

    /**
     * @ORM\ManyToOne(targetEntity="AM\Bundle\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="user", referencedColumnName="id")
     */
    protected $user;


    /**
     * Contract constructor.
     * @param User $user
     */
    public function __construct(User $user)
    {
        $this->user = $user;
        $this->type = static::ANNUAL;
        $this->currency = 'EUR';
        $this->startedAt = new \Datetime('now');
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set amount
     *
     * @param float $amount
     * @return Contract
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * Get amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set startedAt
     *
     * @param \DateTime $startedAt
     * @return Contract
     */
    public function setStartedAt($startedAt)
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    /**
     * Get startedAt
     *
     * @return \DateTime
     */
    public function getStartedAt()
    {
        return $this->startedAt;
    }

    /**
     * Set currency
     *
     * @param string $currency
     * @return Contract
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Get currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Set type
     *
     * @param integer $type
     * @return Contract
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Gets the value of contact.
     *
     * @return Contact
     */
    public function getContact()
    {
        return $this->contact;
    }

    /**
     * Sets the value of contact.
     *
     * @param Contact $contact the contact
     *
     * @return self
     */
    public function setContact(Contact $contact)
    {
        $this->contact = $contact;

        return $this;
    }

    /**
     * Gets the value of user.
     *
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Sets the value of user.
     *
     * @param User $user the user
     *
     * @return self
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get nomarlized amount on one year.
     *
     * @return float
     */
    public function getNormalizedAmount()
    {
        switch ($this->type) {
            case static::ANNUAL:
                return $this->amount;
                break;
            case static::QUARTERLY:
                return $this->amount * 4;
                break;
            case static::BIMONTHLY:
                return $this->amount * 6;
                break;
            case static::MONTHLY:
                return $this->amount * 12;
                break;
            case static::WEEKLY:
                return $this->amount * 52.1775;
                break;

            default:
                return $this->amount;
                break;
        }
    }

    /**
     * @return string
     */
    public function getHumanType()
    {
        return static::$typeToHuman[$this->type];
    }
}

src/AM/Bundle/BillingBundle/Form/ContractType.php
<?php

namespace AM\Bundle\BillingBundle\Form;

use AM\Bundle\BillingBundle\Entity\Contract;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContractType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('amount')
            ->add('startedAt', 'date')
            ->add('currency', 'choice', [
                'label' => 'Currency',
                'choices' => [
                    'EUR' => 'Euro',
                    'USD' => 'US Dollar',
                ]
            ])
            ->add('type', 'choice', [
                'label' => 'Type',
                'choices' => Contract::$typeToHuman,
            ])
            ->add('submit', 'submit', [
                'label' => $options['button_label'],
            ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AM\Bundle\BillingBundle\Entity\Contract',
            'button_label' => 'Create contract',
        ));

        $resolver->addAllowedTypes(array(
            'button_label' => 'string',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'am_bundle_billingbundle_contract';
    }
}

src/AM/Bundle/BillingBundle/Controller/ContractController.php
<?php
/**
 * Copyright © 2015, Ambroise Maupate
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * @file ContractController.php
 * @author Ambroise Maupate
 */
namespace AM\Bundle\BillingBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use AM\Bundle\BillingBundle\Form\ContractType;
use AM\Bundle\BillingBundle\Entity\Contract;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ContractController extends Controller
{
    /**
 * @param Request $request
 * @param $userId
 * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
 */
    public function indexAction(Request $request, $userId)
    {
        if (!$this->isGranted('ROLE_SUPER_ADMIN')) {
            throw $this->createAccessDeniedException();
        }

        $user = $this->get('doctrine')
            ->getManager()
            ->find('AM\Bundle\UserBundle\Entity\User', $userId);

        if (null === $user) {
            throw $this->createNotFoundException();
        }

        $contracts = $this->get('doctrine')
            ->getManager()
            ->getRepository('AM\Bundle\BillingBundle\Entity\Contract')
            ->findBy([
                'user' => $user
            ]);

        $newContract = new Contract($user);
        $addContractForm = $this->createForm(new ContractType(), $newContract);

        $addContractForm->handleRequest($request);
        if ($addContractForm->isValid()) {
            $this->get('doctrine')
                ->getManager()
                ->persist($newContract);
            $this->get('doctrine')
                ->getManager()
                ->flush();

            return $this->redirect($this->generateUrl('am_billing_contracts', ['userId'=>$userId]));
        }

        return $this->render('AMBillingBundle:Contract:index.html.twig', array(
            'user' => $user,
            'contracts' => $contracts,
            'addContractForm' => $addContractForm->createView(),
        ));
    }

    /**
     * @param Request $request
     * @param $userId
     * @param $contractId
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, $userId, $contractId)
    {
        if (!$this->isGranted('ROLE_SUPER_ADMIN')) {
            throw $this->createAccessDeniedException();
        }

        $user = $this->get('doctrine')
            ->getManager()
            ->find('AM\Bundle\UserBundle\Entity\User', $userId);

        $contract = $this->get('doctrine')
            ->getManager()
            ->find('AM\Bundle\BillingBundle\Entity\Contract', $contractId);

        if (null === $user) {
            throw $this->createNotFoundException('User not found');
        }
        if (null === $contract) {
            throw $this->createNotFoundException('Contract not found');
        }

        $editContractForm = $this->createForm(new ContractType(), $contract, array(
            'button_label' => 'Edit contract',
        ));
        $editContractForm->handleRequest($request);
        if ($editContractForm->isValid()) {
            $this->get('doctrine')
                ->getManager()
                ->flush();

            return $this->redirect($this->generateUrl('am_billing_contracts', ['userId'=>$userId]));
        }

        return $this->render('AMBillingBundle:Contract:edit.html.twig', array(
            'user' => $user,
            'editContractForm' => $editContractForm->createView(),
        ));
    }

    /**
     * @param Request $request
     * @param $userId
     * @param $contractId
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function deleteAction(Request $request, $userId, $contractId)
    {
        if (!$this->isGranted('ROLE_SUPER_ADMIN')) {
            throw $this->createAccessDeniedException();
        }

        $user = $this->get('doctrine')
            ->getManager()
            ->find('AM\Bundle\UserBundle\Entity\User', $userId);

        $contract = $this->get('doctrine')
            ->getManager()
            ->find('AM\Bundle\BillingBundle\Entity\Contract', $contractId);

        if (null === $user) {
            throw $this->createNotFoundException('User not found');
        }
        if (null === $contract) {
            throw $this->createNotFoundException('Contract not found');
        }

        $deleteContractForm = $this->createForm('form');
        $deleteContractForm->handleRequest($request);
        if ($deleteContractForm->isValid()) {
            $this->get('doctrine')
                ->getManager()
                ->remove($contract);
            $this->get('doctrine')
                ->getManager()
                ->flush();

            return $this->redirect($this->generateUrl('am_billing_contracts', ['userId'=>$userId]));
        }

        return $this->render('AMBillingBundle:Contract:delete.html.twig', array(
            'user' => $user,
            'deleteContractForm' => $deleteContractForm->createView(),
        ));
    }
}

src/AM/Bundle/BillingBundle/Resources/views/Contract/delete.html.twig
{% extends 'default/index.html.twig' %}

{% set cRoute = app.request.attributes.get('_route') %}

{% block title %}{% trans %}User contracts{% endtrans %}{% endblock %}

{% block content %}
<div class="page-header">
    <div class="navbar-form navbar-right">
        <div class="form-group">

        </div>
    </div>
    <h1>{{ user.username }} — {% trans %}Contracts{% endtrans %}</h1>
</div>

<div class="edit-contract col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title containers-title">{% trans %}Delete a contract{% endtrans %}</h2>
        </div>
        <div class="panel-body">
            {{ form_start(deleteContractForm) }}
            {{ form_widget(deleteContractForm) }}

            <div class="form-group">
                <a href="{{ path('am_billing_contracts', {userId: user.id}) }}" class="btn btn-default">{% trans %}Cancel{% endtrans %}</a>
                <button class="btn btn-danger" type="submit">{% trans %}Confirm contract deletion{% endtrans %}</button>
            </div>
            {{ form_end(deleteContractForm) }}
        </div>
    </div>
</div>

{% endblock %}

src/AM/Bundle/BillingBundle/Resources/views/Contract/edit.html.twig
{% extends 'default/index.html.twig' %}

{% set cRoute = app.request.attributes.get('_route') %}

{% block title %}{% trans %}User contracts{% endtrans %}{% endblock %}

{% block content %}
<div class="page-header">
    <div class="navbar-form navbar-right">
        <div class="form-group">

        </div>
    </div>
    <h1>{{ user.username }} — {% trans %}Contracts{% endtrans %}</h1>
</div>

<div class="edit-contract col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title containers-title">{% trans %}Edit a contract{% endtrans %}</h2>
        </div>
        <div class="panel-body">
            {{ form(editContractForm) }}
        </div>
    </div>
</div>

{% endblock %}

src/AM/Bundle/BillingBundle/Resources/views/Contract/index.html.twig
{% extends 'default/index.html.twig' %}

{% set cRoute = app.request.attributes.get('_route') %}

{% block title %}{% trans %}User contracts{% endtrans %}{% endblock %}

{% block content %}
<div class="page-header">
    <div class="navbar-form navbar-right">
        <div class="form-group">

        </div>
    </div>
    <h1>{{ user.username }} — {% trans %}Contracts{% endtrans %}</h1>
</div>
<div class="instances col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title containers-title">{% trans %}Active contracts{% endtrans %}</h2>
        </div>
        <table class="panel-body table">
            <tr>
                <th>{% trans %}Contract ID{% endtrans %}</th>
                <th>{% trans %}Started at{% endtrans %}</th>
                <th>{% trans %}Amount{% endtrans %}</th>
                <th>{% trans %}Type{% endtrans %}</th>
                <th></th>
            </tr>
            {% for contract in contracts %}
                    <tr>
                        <td>{{ contract.id }}</td>
                        <td>{{ contract.startedAt|localizeddate('medium', 'none') }}</td>
                        <td>{{ contract.amount|localizedcurrency(contract.currency) }}</td>
                        <td>{{ contract.humanType }}</td>
                        <td>
                            <a href="{{ path('am_billing_contracts_edit', {
                                'userId': user.id,
                                'contractId': contract.id
                            }) }}" class="btn btn-default btn-xs">{% trans %}Edit{% endtrans %}</a>
                            <a href="{{ path('am_billing_contracts_delete', {
                                'userId': user.id,
                                'contractId': contract.id
                            }) }}" class="btn btn-danger btn-xs">{% trans %}Delete{% endtrans %}</a>

                        </td>
                    </tr>
            {% else %}
                <tr class="no-containers"><td colspan="5"><em>{% trans %}No contract linked{% endtrans %}</em></td></tr>
            {% endfor %}
        </table>
    </div>
</div>
<div class="add-contract col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title containers-title">{% trans %}Add a contract{% endtrans %}</h2>
        </div>
        <div class="panel-body">
            {{ form(addContractForm) }}
        </div>
    </div>
</div>

{% endblock %}